### ISSUE TITLE
Neo3 Discussion

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#571]
This issue can be used to discuss and break down outstanding features for the initial Neo3 release of neon.js

Current needs are as follows:
* [High Priority] api package maturity (this can be further defined using an audit of the neon wallet)
* [High Priority] system and network fee calculations
* [High Priority] documentation maturity
* [Medium Priority] tsdoc
* [Medium Priority] contract manifest-based field validation
* [Medium Priority] test expansion
* [Low Priority] notifications (this may be a feature we could add support for in a later release by adding dora api support)

@snowypowers @comountainclimber let me know if I missed anything or there is any discrepancy on priority.

**Comment by ixje** [comment]
I've had a look at the following item
> [High Priority] system and network fee calculations

The gas consumption for system fee can be obtained via RPC using [invokescript](https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/invokescript.html). The network fee is where it gets interesting. 

Network fee = transaction base size + sum(signer's scripts) * fee per byte. ([ref](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L369-L432))

A signer script can be 1 of 3 things
1) a single signature redeem script
2) a multi signature redeem script
3) an actual smart contract with a verification function

The fee of the first 2 can be statically determined ([ref](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L410-L426)). The fee of the smart contract (3) requires [running the VM](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L397-L408) (similar to what we need todo for system fee). The problem here is that it needs to run the VM using the `Verification` trigger [type](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/TriggerType.cs#L9-L16), whereas all RPC calls only allow running with the `Application` trigger type. 

Assuming I didn't miss anything the only short term feasible solution I see is having an RPC call that allows running the VM with the Verification trigger type. This can either be modifying the `invokescript` call to allow specifying a trigger type or a whole new RPC call. Anyone sees a different solution? @lllwvlvwlll @snowypowers 
If not, then I'll start the discussion on the NEO project repository.

### Task break down
As for supporting what is currently possible, I see the following tasks
- [ ] fix transaction size calculation.

   e.g. the [Signer](https://github.com/CityOfZion/neon-js/blob/1d9f61d7c1db4f9c202f0120b53ac38bf73fd51b/packages/neon-core/src/tx/components/Signer.ts) class currently returns a wrong size if `allowedContracts` or `allowedGroups`  is specified. 

   solution: implement the equivalent of the C#'s [GetVarSize()](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/IO/Helper.cs#L99-L142) and applying it to all transaction properties where required. For the `Signer` case you might want to look at what the `Witness` class is doing. Although I personally prefer a helper function because it is not an uncommon function afaik. @snowypowers do you have any preference how to solve it?
- [ ] implement helper function to detect if the signer script is a `single signature redeemscript` ([reference implementation](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/Helper.cs#L105))
- [ ] implement helper function to detect if the signer script is a `multi signature redeemscript` ([reference implementation](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/Helper.cs#L48))
- [ ] if all previous are done; implement network fee calculation function. 
For the time being I'd probably throw an error if we require smart contract (case 3) until supported.

**Comment by snowypowers** [comment]
I have not seen any functionality that would allow me to run the VM in verification mode. 

I see that I have messed up the `size` method by forgetting the array length byte. The alternative implementation would be to pay the serialization cost and then read the actual size of the serialized output. This would make it easier from the development viewpoint since we will only need to manage a single source of truth. 

The rest of the tasks looks good to me. The VM issue does not seem to be blocker as the default use case at the moment should not require the custom verification.

Looks like C# needs a disassembler too.

**Comment by ixje** [comment]
Dropping a comment here to avoid duplicating work. Atm I can successfully build, sign and send a transaction via the `sendrawtransaction` RPC call for transferring NEO or GAS using a single signature redeem script. Next, I first want to add support for multi-signature redeem scripts (specifically the code for calculating the correct network fee). 

Related: #592 (#581, #591)

**Comment by ixje** [comment]
I think this one is obsolete now that we have our formal N3 release. Ping if you think otherwise and it can be re-opened
