### ISSUE TITLE
System and Network Fee Calculations

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#581]
from https://github.com/CityOfZion/neon-js/issues/571#issuecomment-698908831

I've had a look at the following item
> [High Priority] system and network fee calculations

The gas consumption for system fee can be obtained via RPC using [invokescript](https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/invokescript.html). The network fee is where it gets interesting. 

Network fee = transaction base size + sum(signer's scripts) * fee per byte. ([ref](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L369-L432))

A signer script can be 1 of 3 things
1) a single signature redeem script
2) a multi signature redeem script
3) an actual smart contract with a verification function

The fee of the first 2 can be statically determined ([ref](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L410-L426)). The fee of the smart contract (3) requires [running the VM](https://github.com/neo-project/neo/blob/9a160c4d249efb7364c9dbbed847fa1ded72604b/src/neo/Wallets/Wallet.cs#L397-L408) (similar to what we need todo for system fee). The problem here is that it needs to run the VM using the `Verification` trigger [type](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/TriggerType.cs#L9-L16), whereas all RPC calls only allow running with the `Application` trigger type. 

Assuming I didn't miss anything the only short term feasible solution I see is having an RPC call that allows running the VM with the Verification trigger type. This can either be modifying the `invokescript` call to allow specifying a trigger type or a whole new RPC call. Anyone sees a different solution? @lllwvlvwlll @snowypowers 
If not, then I'll start the discussion on the NEO project repository.

### Task break down
As for supporting what is currently possible, I see the following tasks
- [ ] fix transaction size calculation.

   e.g. the [Signer](https://github.com/CityOfZion/neon-js/blob/1d9f61d7c1db4f9c202f0120b53ac38bf73fd51b/packages/neon-core/src/tx/components/Signer.ts) class currently returns a wrong size if `allowedContracts` or `allowedGroups`  is specified. 

   solution: implement the equivalent of the C#'s [GetVarSize()](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/IO/Helper.cs#L99-L142) and applying it to all transaction properties where required. For the `Signer` case you might want to look at what the `Witness` class is doing. Although I personally prefer a helper function because it is not an uncommon function afaik. @snowypowers do you have any preference how to solve it?
- [ ] implement helper function to detect if the signer script is a `single signature redeemscript` ([reference implementation](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/Helper.cs#L105))
- [ ] implement helper function to detect if the signer script is a `multi signature redeemscript` ([reference implementation](https://github.com/neo-project/neo/blob/588cd983250f97659c6f91d7cd76ca7ff7e82990/src/neo/SmartContract/Helper.cs#L48))
- [ ] if all previous are done; implement network fee calculation function. 
For the time being I'd probably throw an error if we require smart contract (case 3) until supported.

**Comment by ixje** [comment]
>> For the Signer case you might want to look at what the Witness class is doing. Although I personally prefer a helper function because it is not an uncommon function afaik. snowypowers do you have any preference how to solve it?

> I see that I have messed up the size method by forgetting the array length byte. The alternative implementation would be to pay the serialization cost and then read the actual size of the serialized output. This would make it easier from the development viewpoint since we will only need to manage a single source of truth.

**Comment by kjlevitz** [comment]
https://github.com/kjlevitz/neon-js/blob/next/helpers/signatureVerification.ts

Current verification helper that I have been working on. If this looks good for single and multi-sig I can create a PR to next branch,

**Comment by lllwvlvwlll** [comment]
resolved
