### ISSUE TITLE
RC2 todo

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neon-js#691]
- [x] 1. https://github.com/neo-project/neo/commit/8fe3dbb962c78979b3f2de85ce1499c1510493a2 (breaking all addresses again 😡 )
- [x] 2. rename `DesignationContract` to `RoleManagement` https://github.com/CityOfZion/neon-js/pull/690#discussion_r598056845
- [x] 3. ~~https://github.com/neo-project/neo/pull/2407~~ (doesn't actually affect neon-js)
- [x] 4. https://github.com/neo-project/neo/pull/2440
- [x] 5. https://github.com/neo-project/neo/pull/2435
- [x] 6. https://github.com/neo-project/neo/pull/2420
- [ ] 7. Update release documentation

**Comment by snowypowers** [comment]
I have pushed out a rc2 docker container so development can start. The docker container might be a little unstable since it uses a mix of rc2 and slightly older neo-modules plugins but it looks like it should work for our purposes.

**Comment by ixje** [comment]
Thanks! I don't expect to work on anything this week and perhaps not next week, but we'll see.

**Comment by ixje** [comment]
Note I made a `feature-rc2` branch from `next` so that individual items from the list can be PR'd against that.

**Comment by ixje** [comment]
I'm going to create a single PR for all RC2 changes soon
